- src/app/auth/callback/route.ts
- src/components/Home/Home.tsx
- src/components/auth/StacksAuth.tsx
- src/utils/supabase/client.ts
- src/utils/supabase/middleware.ts
- src/utils/supabase/server.ts
- src/utils/utils.ts
This PR introduces wallet sign-up/sign-in.
> feat: added wallet authentication

- src/components/auth/StacksAuth.tsx
> Fix replit build errors

- src/components/agents/AgentForm.tsx
New tools on one side mean new tools here too!
Related to aibtcdev/aibtcdev-backend#8
> Update tools to match backend

- src/app/dashboard/page.tsx
fix issue https://github.com/aibtcdev/aibtcdev-frontend/issues/24
> fix: change the height of dashboard layout

- src/app/admin/layout.tsx
- src/app/admin/page.tsx
- src/app/leaderboard/page.tsx
- src/components/reusables/Navbar.tsx
- src/middleware.ts
- src/utils/supabase/middleware.ts
This PR introduces an admin panel. Users with the admin role can view this panel and assign agent addresses to participants. Additionally, admins can assign roles to users. The table can be filtered by roles, and users can search using STX addresses.
> fix: update leaderboard, admin panel and nav

- .vscode/extensions.json
- .vscode/settings.json
- package-lock.json
- package.json
- src/app/dashboard/page.tsx
- src/components/crews/CloneTradingAnalyzer.tsx
- src/components/crews/CrewForm.tsx
- src/components/crews/CrewManagement.tsx
- src/components/dashboard/Dashboard.tsx
Users are now able to clone our trading analyzer. Once they've cloned it they can update and edit the agents and tasks and execute them (haven't tried executing myself though). They cannot clone it multiple time. Need to update the prompts for them.
> feat: able to clone our trading analyzer

- src/components/reusables/Disclaimer.tsx
- src/components/reusables/Footer.tsx
Part of aibtcdev/aibtcdev-backend#12
> Add disclaimer

- src/app/crew/[id]/chat/page.tsx
- src/app/crew/[id]/layout.tsx
- src/app/crew/[id]/manage/page.tsx
- src/app/crew/[id]/page.tsx
- src/components/agents/AgentForm.tsx
- src/components/agents/AgentManagement.tsx
- src/components/crews/CloneTradingAnalyzer.tsx
- src/components/crews/CrewManagement.tsx
- src/components/dashboard/Dashboard.tsx
- src/components/dashboard/DashboardChat.tsx
- src/components/dashboard/Execution.tsx
- src/components/tasks/TaskManagement.tsx
> Add chat with crews

- src/components/dashboard/Dashboard.tsx
- src/components/dashboard/Execution.tsx
- Implement useCallback to prevent unnecessary function recreation
- Fix useEffect dependency array warnings
- Add session management to execute_crew function
- Wrap callback functions in useCallback to prevent redundant rerenders
> fix: usecallback to fix unnecessary recreation, added session 

- src/app/fetch/route.ts
- src/app/layout.tsx
- src/app/leaderboard/page.tsx
- src/app/providers.tsx
- src/components/reusables/Navbar.tsx
- src/hooks/useLeaderBoardData.ts
- src/hooks/useUserData.ts
- Used TanStack Query for data fetching and caching.
- Utilized Hiro API to fetch the balance.
- Created hooks for the leaderboard and user profile.
- Developed a route to fetch the balance from the Hiro Stacks API.
> fix: use tanstack query to fetch balances

- src/app/crew/[id]/chat/page.tsx
Frontend backend talking now from chat.
> fix: added sessions to chat

- src/app/crew/[id]/page.tsx
- src/components/agents/AgentForm.tsx
- src/components/crews/CloneTradingAnalyzer.tsx
- src/lib/tools.ts
Uses the `/tools` endpoint in the backend instead of keeping a separate list here that has to match.
> Load dynamic tools

- src/components/dashboard/DashboardChat.tsx
Displays agent responses nicely, probably can type/handle better.
> Fix streaming display

- src/components/agents/AgentForm.tsx
- src/components/dashboard/Dashboard.tsx
fix #82 and update the ui for tools selection
> fix(ui): remove duplicate add-crew | display agent tools

- src/components/dashboard/DashboardChat.tsx
No more parsing error. 
Close the connection when the result is obtained so no more retries/error display after the result is obtained.
> fix(parsing): No more parsing errors now

- src/hooks/useLeaderBoardData.ts
Shows admins in the leaderboard too.
> fix(leaderboard): shows admin to the leaderboard

- src/app/admin/page.tsx
> fix(admin): updated code logic

- src/components/stats-chart/StatsChart.tsx
make the public-stats mobile responsive
> fix: chat height

- src/components/stats-chart/StatsChart.tsx
Some small refinements to test preview with cloudflare
> Update stats page

- src/hooks/useChat.ts
This is just a quick fix to allow me to merge in the backend which now will support both backend types with the ability to switch type as ENV variable when we are ready for new backend.
> Remove Endpoints for Backend for Chat

- src/app/agents/page.tsx
- src/app/application-layout.tsx
- src/app/daos/[id]/layout-client.tsx
- src/app/daos/[id]/proposals/page.tsx
- src/app/globals.css
- src/components/chat/agent-selector.tsx
- src/components/chat/chat-input.tsx
- src/components/chat/chat-message-bubble.tsx
- src/components/chat/chat-window.tsx
- src/components/daos/dao-extensions.tsx
- src/components/daos/dao-overview.tsx
- src/components/daos/dao-proposals.tsx
- src/components/profile/profile-view.tsx
- src/components/tasks/cron-schedule-selector.tsx
- src/components/tasks/jobs-table.tsx
- src/components/tasks/task-edit-modal.tsx
- src/components/threads/CreateThreadButton.tsx
- src/components/threads/thread-list.tsx
New layout for the chat and desktop for better UX.
> New layout

- src/components/daos/dao-proposals.tsx
- src/components/daos/daos.tsx
This matches what we have in the DB, could definitely see changing the fields up but will fix the application errors for now.
> Use correct proposal types

- src/app/application-layout.tsx
- src/app/chat/page.tsx
- src/components/chat/agent-selector.tsx
- src/components/chat/chat-input.tsx
- src/components/chat/chat-message-bubble.tsx
- src/components/chat/chat-window.tsx
- src/components/chat/message-list.tsx
- src/components/threads/thread-list.tsx
- src/hooks/use-profile.ts
- src/lib/address.ts
- src/store/chat.ts
uses local storage for chat and agent persistent.
> fix: add agent persist and chat persist

- src/components/agents/agent-details-panel.tsx
> fix: agent balance not displaying after reload

- src/app/daos/[id]/page.tsx
- src/components/auth/auth-signout.tsx
- src/components/auth/auth-stacks.tsx
- src/components/daos/daos-table.tsx
- src/components/daos/proposal/DAOProposal.tsx
- src/components/daos/proposal/ProposalCard.tsx
- src/components/daos/proposal/ProposalMetrics.tsx
- src/components/daos/proposal/TimeStatus.tsx
- src/components/daos/proposal/VoteProgress.tsx
- src/lib/vote-utils.ts
- src/queries/daoQueries.ts
> Fix fix fix

- src/app/providers.tsx
- src/components/daos/daos.tsx
- src/components/profile/agent-prompt-form.tsx
- src/components/profile/profile-view.tsx
- src/components/reusables/asset-tracker.tsx
- src/lib/vote-utils.ts
- src/queries/daoQueries.ts
> fix: add cache url in env

- src/app/daos/[name]/layout-client.tsx
- src/app/daos/[name]/page.tsx
- src/components/agents/dao-agent.ts
- src/components/daos/daos-table.tsx
- src/helpers/format-mission.tsx
- src/queries/dao-queries.ts
Latest iteration, more info in https://github.com/aibtcdev/agent-tools-ts/issues/132
> Replace MEDIA3 with FACE3

- src/components/daos/DaoExtensions.tsx
Related to #384 testing out a redesign before we remove completely.
I like the fact that the DAO is on-chain, comprised of a set of contracts, and that those can be clicked through / viewed by power users.
> Update extensions page

- src/app/application-layout.tsx
This pull request addresses inconsistencies between the mobile and desktop navigation menus and improves the user experience
of the header dropdowns.
Key Changes:
* Mobile Navigation Parity: The user dropdown menu in the mobile view now includes the "Account Settings" and "Deposit"
links, making it consistent with the desktop layout. This ensures users have access to the same navigation options
regardless of their device.
* Auto-Closing Dropdowns: Implemented state management to ensure that both mobile and desktop dropdown menus automatically
close after a navigation link is clicked. This creates a more intuitive and seamless user flow.
* Protected `/deposit` Route: Added the /deposit route to the list of protected routes. This ensures that unauthenticated
users are prompted to log in …
> Fix: Align Mobile/Desktop Nav and Improve Dropdown UX

- package-lock.json
- package.json
- src/components/account/ApproveAsset.tsx
- src/components/account/ApproveContract.tsx
- src/components/daos/DAOPage.tsx
- src/components/proposals/ProposalSubmission.tsx
WIP - depends on aibtcdev/aibtcdev-backend#333
> Approve contract types

- src/app/proposals/[id]/page.tsx
- src/components/proposals/ProposalDetails.tsx
- src/components/proposals/VotesTable.tsx
- src/components/proposals/data-table/DataTable.tsx
- src/components/proposals/empty-states/ProposalEmptyStates.tsx
- src/components/proposals/layout/FixedActionBar.tsx
- src/components/proposals/layout/ProposalSection.tsx
- src/components/proposals/layout/ProposalSidebar.tsx
- src/components/proposals/sections/ChainSection.tsx
- src/components/proposals/sections/MessageSection.tsx
- src/components/proposals/sections/VetosSection.tsx
- src/components/proposals/sections/VotesSection.tsx
- src/components/proposals/sections/VotingSection.tsx
- src/components/proposals/skeletons/ProposalSkeletons.tsx
- src/hooks/useVetos.ts
- src/services/index.ts
- src/services/veto.service.ts
- src/types/index.ts
- src/types/veto.ts
This reverts commit c9ea332c50af9acedf66b964a631debddc0d4bb8.
> Revert "Revert "add vetos""

- src/components/btc-deposit/DepositForm.tsx
Should help with #620 and maybe #651
> Update post conditions in buy
